x-common-env: &common-env
  - GITHUB_TOKEN
  - GITEA_URL
  - GITEA_TOKEN
  - ACCESS_TOKEN
  - GITLAB_URL
  - GITLAB_TOKEN
  - BITBUCKET_WORKSPACE
  - BITBUCKET_USERNAME
  - BITBUCKET_APP_PASSWORD
  - FORGEJO_URL
  - FORGEJO_TOKEN

services:
  app:
    build: .
    environment: *common-env

  test:
    build: .
    entrypoint: ["python", "-m", "pytest"]
    command: ["tests/", "-v"]
    environment: *common-env
