x-common-env: &common-env
  - GITHUB_TOKEN
  - GITEA_URL
  - GITEA_TOKEN
  - ACCESS_TOKEN
  - GITLAB_URL
  - GITLAB_TOKEN
  - BITBUCKET_WORKSPACE
  - BITBUCKET_USERNAME
  - BITBUCKET_APP_PASSWORD
  - FORGEJO_URL
  - FORGEJO_TOKEN

services:
  app:
    build: .
    image: gitporter:latest
    restart: "no"
    environment: *common-env
    env_file:
      - path: .env
        required: false

  test:
    build: .
    image: gitporter:latest
    restart: "no"
    entrypoint: ["python", "-m", "pytest"]
    command: ["tests/", "-v"]
    environment: *common-env
    env_file:
      - path: .env
        required: false
    profiles:
      - test
